## Data Manipulation using Pytorch

*Following are curated as self study notes from the readings of online book [Deep Dive into Deep Learning](https://d2l.ai/chapter_preliminaries/ndarray.html). Alongside with my personal notes wherever I needed more explaination to keep for later reference.*

**A tensor represents a (possibly multi-dimensional) array of numerical values**

- Package to import `torch`
- Tensor 1 Axes ~ Vector
- Tensor 2 Axes ~ Matrix
- Tensor With K axes ~ object as a Kth order tensor 
- Unless otherwise specified, new tensors are stored in main memory and designated for CPU-based computation.


In [4]:
import torch

x = torch.arange(12, dtype = torch.float32)
x # Note - 0 is included, 12 is excluded, spaced by 1, prints a series upto 11.

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.numel() # Size of the elements

12

In [7]:
x.shape #a tensor’s shape (the length along each axis) by inspecting its shape attribute

torch.Size([12])

In [8]:
X = x.reshape(3, 4) #change the shape of a tensor without altering its size or values, by invoking reshape
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
torch.zeros((2, 3, 4)) #Practitioners often need to work with tensors initialized to contain all zeros or ones

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2, 3, 4)) #we can create a tensor with all ones by invoking ones.

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
torch.randn(2, 3, 4)

tensor([[[-0.0795, -0.2561, -0.8737,  0.5461],
         [ 0.5143,  1.1183, -0.4634,  0.7963],
         [-1.2618, -1.2886, -0.3583, -0.4733]],

        [[-0.9096, -2.6475, -0.0294,  0.7994],
         [-0.6947, -0.4350,  0.6657, -0.4991],
         [ 0.5117,  0.7535,  1.4867, -0.2024]]])

In [12]:
torch.randn(2, 3)

tensor([[ 0.5424, -1.1933,  1.6353],
        [ 0.8635, -0.1641,  0.0671]])

## torch.randn() and difference between `torch.randn((2, 3, 4))` and `torch.randn(2, 3)`

`torch.randn()` is a function used to generate random numbers from a normal distribution with a mean of 0 and a standard deviation of 1. The function generates random numbers based on the shape specified in the input arguments. Let's break down the differences between `torch.randn((2, 3, 4))` and `torch.randn(2, 3)`:

1. `torch.randn((2, 3, 4))`:
   - This syntax creates a 3-dimensional tensor with a shape of `(2, 3, 4)`.
   - The function generates random numbers from a standard normal distribution (mean=0, std=1) and arranges them into a tensor with the specified shape.

   For example:
   ```
   tensor([[[-0.1473,  1.0817,  0.4241, -0.2850],
            [ 0.2577,  1.6705,  0.1176,  0.1603],
            [-1.3135, -0.4098, -1.8831, -0.7269]],

           [[-1.5825, -0.2327,  0.2387, -0.4960],
            [ 1.4255, -0.4050, -1.2385,  0.6178],
            [ 0.0446,  0.5943,  1.8471,  1.0647]]])
   ```

2. `torch.randn(2, 3)`:
   - This syntax creates a 2-dimensional tensor with a shape of `(2, 3)`.
   - The function generates random numbers from a standard normal distribution (mean=0, std=1) and arranges them into a 2D tensor with the specified shape.

   For example:
   ```
   tensor([[-0.5634, -1.1082,  1.2536],
           [ 0.7942,  0.0482, -0.2921]])
   ```

In summary, the key difference between the two is the shape of the resulting tensor. The first call, `torch.randn((2, 3, 4))`, generates a 3D tensor with dimensions (2, 3, 4), while the second call, `torch.randn(2, 3)`, generates a 2D tensor with dimensions (2, 3). The numbers within the tensors are random samples from the standard normal distribution.

In [15]:
torch.tensor([[2, 3, 4], [5, 6, 7], [8, 9, 0]]) #construct tensors by supplying the exact values for each element by supplying (possibly nested) Python list(s) containing numerical literals.

tensor([[2, 3, 4],
        [5, 6, 7],
        [8, 9, 0]])