In [2]:
import numpy as np
import matplotlib.pyplot as plt
print('Setup Complete')

Setup Complete


## Scalars

### In PyTorch

In [3]:
import torch

x = torch.tensor(25)
x

tensor(25)

In [5]:
x.shape # Note the emtpy square brackets meaning, no dimensions, hence scalar

torch.Size([])

## Vector = Rank 1 Tensor

### In Numpy

In [6]:
x_np = np.array([36, 3, 6])
x_np

array([36,  3,  6])

In [7]:
len(x_np)

3

In [8]:
x_np.shape

(3,)

In [9]:
type(x_np)

numpy.ndarray

In [10]:
type(x_np[0])

numpy.int64

## Transposing Vector

In [11]:
x_np_t = x_np.T
x_np_t

array([36,  3,  6])

In [12]:
x_np_t.shape

(3,)

In [13]:
y = np.array([[36, 3, 6]])
y

array([[36,  3,  6]])

In [14]:
y.shape

(1, 3)

In [15]:
y_t = y.T
y_t

array([[36],
       [ 3],
       [ 6]])

In [16]:
y_t.shape

(3, 1)

In [17]:
y_t.T

array([[36,  3,  6]])

In [18]:
y_t.T.shape

(1, 3)

### In PyTorch

In [20]:
x_pt = torch.tensor([36, 3, 6])
x_pt

tensor([36,  3,  6])

## Zero vectors

In [19]:
zeroes = np.zeros(4)
zeroes

array([0., 0., 0., 0.])

### $L^2$ Norm

In [21]:
x_np

array([36,  3,  6])

In [22]:
np.linalg.norm(x_np)

36.61966684720111

### $L^1$ Norm

In [23]:
x_np

array([36,  3,  6])

In [24]:
np.abs(36) + np.abs(3) + np.abs(6)

45

### Squared $L^2$ Norm

In [25]:
x_np

array([36,  3,  6])

In [27]:
(36**2 + 3**2 + 6**2)

1341

In [26]:
np.dot(x_np, x_np)

1341

### Max Norm

In [28]:
x_np

array([36,  3,  6])

In [29]:
np.max([np.abs(36), np.abs(2), np.abs(5)])

36